Include playbooks in main.yml
trishnaguha/build-atomic-host pull request #10
Opened 2017-02-10 09:37 UTC by trishnaguha

@gbraad Here are some improvements of the repo. We still have `rebase.yml` separate which I'm going to push later.

2017-02-10 09:51 UTC, gbraad commented on compose.yml
> +  command:
packages can be installed with an ansible module...

2017-02-10 09:52 UTC, gbraad commented on compose.yml
> +  package: name={{ item }} state=installed
requirements in a separate playbook?

2017-02-10 09:52 UTC, gbraad commented on compose.yml
> +  package: name={{ item }} state=installed
requirements in a separate playbook?

2017-02-10 09:54 UTC, trishnaguha commented on compose.yml
> +  package: name={{ item }} state=installed
Sure.

2017-02-10 10:03 UTC, trishnaguha commented on compose.yml
> +  command:
@gbraad `daemon` module needs to installed with rpm on fedora. It is not available for dnf.

2017-02-10 10:04 UTC, gbraad commented on compose.yml
> +- name: Download daemon rpm
download to /tmp maybe ? Then you also do not need the ignore.

2017-02-10 10:04 UTC, gbraad commented on compose.yml
> +    rpm --install ./daemon-0.6.4-1.x86_64.rpm
really not available in epel? or rpmfusion? hmmmm

2017-02-10 10:05 UTC, gbraad requested changes
Please see comments.

2017-02-10 10:22 UTC, trishnaguha commented on requirements.yml
> +  ignore_errors: yes
I'm using `ignore_errors` so that the playbook won't fail if `daemon` is already installed.

2017-02-10 10:23 UTC, trishnaguha commented
@gbraad Pushed the changes.

2017-02-10 10:29 UTC, gbraad commented on requirements.yml
> +  ignore_errors: yes
you could consider combining all steps in one go...

```yaml
- name: Install daemon package
   command: >-
      wget ...
      rpm ....
      rm ...
   ignore_errors: yes
```

2017-02-10 10:31 UTC, trishnaguha commented on requirements.yml
> +  ignore_errors: yes
I thought to use `get_url` module instead of `wget command` ;-).

2017-02-10 10:36 UTC, gbraad commented on requirements.yml
> +  ignore_errors: yes
I considered proposing this, but sometimes it is a tradeoff to make. It is a single step that can be skipped with a tag in future... or do we want to be explicit and show each individual action. If you can make it work, please go ahead 👍

2017-02-10 10:38 UTC, trishnaguha commented on requirements.yml
> +  ignore_errors: yes
Cool. I'm fine with either option. Not a big deal. Let me update it.

2017-02-12 12:19 UTC, trishnaguha commented
@gbraad How does this diff look on including `rebase.yml` ?

```
[tguha@localhost build-atomic-host]$ git diff
diff --git a/main.yml b/main.yml
index 8e676b7..f06608d 100644
--- a/main.yml
+++ b/main.yml
@@ -8,3 +8,13 @@
   - include: requirements.yml
diff --git a/main.yml b/main.yml
index 8e676b7..f06608d 100644
--- a/main.yml
+++ b/main.yml
@@ -8,3 +8,13 @@
   - include: requirements.yml
   - include: compose.yml
   - include: ssh-setup.yml
+
+- name: Rebase
+  hosts: atomichost
+  become: yes
+  become_method: sudo
+
+  tasks:
+  - include: rebase.yml
+    vars:
+      httpserver: 192.168.122.1
diff --git a/rebase.yml b/rebase.yml
index 02ff6b9..2da028d 100644
--- a/rebase.yml
+++ b/rebase.yml
@@ -1,14 +1,8 @@
 ---
-- name: Rebase On the Tree
-  hosts: atomichost
-  become: yes
-  become_method: sudo
+- name: Create remote named my-atomic
+  command:
+    ostree remote add my-atomic http://"{{ httpserver }}":35000/repo --no-gpg-verify
 
-  tasks:
-  - name: Create remote named my-atomic
-    command:
-      ostree remote add my-atomic http://'{{ httpserver }}':35000/repo --no-gpg-verify
-
-  - name: Rebase on to my tree
-    command:
-      rpm-ostree rebase my-atomic:fedora-atomic/25/x86_64/docker-host
+- name: Rebase on to my tree
+  command:
+    rpm-ostree rebase my-atomic:fedora-atomic/25/x86_64/docker-host
```

2017-02-13 08:30 UTC, trishnaguha commented
Merging this in as now I have other changes to this repo which will not create `inventory` file anymore.
I'll create a separate PR for that. Thanks for the review :-).

2017-02-13 08:30 UTC, merged