Customize packages which OSTree will compose
trishnaguha/build-atomic-host pull request #20
Opened 2017-02-23 10:39 UTC by trishnaguha

Fixes #17

2017-02-27 08:16 UTC, gbraad commented on compose.yml
> +  lineinfile:
this works, but maybe writing to a new file... and composing this file would be a cleaner approach. WDYT?

2017-02-27 10:36 UTC, trishnaguha commented on compose.yml
> +  lineinfile:
@gbraad Do you mean simply creating a copy of the json file and edit that? 
If you meant this, +1 from my side.

2017-02-27 10:38 UTC, trishnaguha commented on compose.yml
> +  lineinfile:
We should also add it to `.gitignore` in that case.

2017-02-27 12:40 UTC, gbraad commented on compose.yml
> +  lineinfile:
You would not create a copy, but a child: https://gitlab.com/gbraad/ceph-atomic/blob/downstream/ceph-atomic-host.json The key would be to use: `"include": "centos-atomic-host.json",` to create the relationship.

2017-02-28 10:47 UTC, trishnaguha commented on compose.yml
> +  lineinfile:
@gbraad Pushed the changes.

2017-02-28 14:01 UTC, gbraad commented on compose.yml
> +  lineinfile:
can you use a ninja2 template for this instead?

2017-02-28 14:01 UTC, gbraad requested changes
use a template instead

2017-02-28 14:53 UTC, trishnaguha commented
@gbraad It is composing the file `customized-atomic-docker-host.json` which includes `fedora-atomic-docker-host.json`.

2017-02-28 14:54 UTC, trishnaguha commented on compose.yml
> +    line='{\n    "include"{{':'}} "fedora-atomic-docker-host.json",\n    "packages"{{':'}} [\n        {{ packages }}\n    ]\n}'
This is going to add the var `packages` in the json file created.

2017-02-28 14:58 UTC, gbraad commented
https://suspicious.website/2015/02/18/generating-config-files-with-ansible-and-jinja2/

2017-03-01 07:54 UTC, trishnaguha commented on compose.yml
> +    line='{\n    "include"{{':'}} "fedora-atomic-docker-host.json",\n    "packages"{{':'}} [\n        {{ packages }}\n    ]\n}'
@gbraad Pushed with the requested changes. Can you review now?

2017-03-01 07:56 UTC, gbraad commented on templates/customized-packages-template.j2
> +    "include":"fedora-atomic-docker-host.json",
I would also consider this to be provided as a variable ;-)

2017-03-01 07:56 UTC, gbraad commented on compose.yml
> +- name: Create JSON file for adding packages
Is this necessary?

2017-03-01 07:57 UTC, gbraad commented on compose.yml
>      repo=https://pagure.io/fedora-atomic.git
possibly provide this as a variable too...

2017-03-01 07:57 UTC, gbraad commented on compose.yml
>      version=f25
ditto

2017-03-01 07:57 UTC, gbraad commented on compose.yml
>      dest=/workspace/fedora-atomic
ditto

2017-03-01 07:58 UTC, gbraad commented on compose.yml
>      chdir=/workspace/fedora-atomic
ditto

2017-03-01 07:58 UTC, gbraad commented on compose.yml
> +    dest: /workspace/fedora-atomic/customized-atomic-docker-host.json
part of the possible variable

2017-03-01 07:58 UTC, gbraad requested changes
Please consider extracting variables

2017-03-01 10:43 UTC, trishnaguha commented
@gbraad Pushed the changes :-).

2017-03-01 11:27 UTC, gbraad commented on README.md
> +version: f25
branch indicate it better

2017-03-01 11:28 UTC, gbraad commented on README.md
> +repodir: fedora-atomic
full path indicates more meaningful information and allows to be more flexible

2017-03-01 11:29 UTC, gbraad commented on README.md
> +localcompose: customized-atomic-docker-host.json
isn't the compose always local? so, what does the file really mean?

2017-03-01 11:30 UTC, gbraad commented on README.md
> +sourcecompose: fedora-atomic-docker-host.json
look at the documentation for the naming of these files.

2017-03-01 11:31 UTC, trishnaguha commented on README.md
> +localcompose: customized-atomic-docker-host.json
Wasn't sure what to name it. I have named the json file cloned from source as `sourcecompose`.

2017-03-01 12:35 UTC, trishnaguha commented
@gbraad Looks good now?

2017-03-01 13:55 UTC, gbraad commented on README.md
> +coremanifest: customized-atomic-docker-host.json      # The manifest that goes into the custom host(ostree) content that we are going to build.
core? why not custom?
Maybe I have it wrong, but core sounds off...

2017-03-01 13:57 UTC, trishnaguha commented on README.md
> +coremanifest: customized-atomic-docker-host.json      # The manifest that goes into the custom host(ostree) content that we are going to build.
We can name it `custommanifest`. IMO `coremanifest` sounds better since this is core manifest file we are using for the compose.

2017-03-02 05:41 UTC, gbraad commented on README.md
> +coremanifest: customized-atomic-docker-host.json      # The manifest that goes into the custom host(ostree) content that we are going to build.
but in this context it is a derived version. coremanifest can therefore be misunderstood for it's purpose.

2017-03-02 05:42 UTC, trishnaguha commented on README.md
> +coremanifest: customized-atomic-docker-host.json      # The manifest that goes into the custom host(ostree) content that we are going to build.
OK.

2017-03-04 01:59 UTC, gbraad commented
Can you run this again on a clean install, and show me the output?

2017-03-04 08:11 UTC, trishnaguha commented
@gbraad I have tested this on a new instance: 
Following is the output:

![screenshot from 2017-03-04 13-40-46](https://cloud.githubusercontent.com/assets/13337039/23577258/4464f5f6-00e0-11e7-81b0-b703459e71fa.png)

2017-03-04 13:32 UTC, gbraad approved these changes

2017-03-04 13:46 UTC, merged